
NAME = dht-test
BOARD = nodemcu
SERIAL_PORT = /dev/ttyS6
BAUDRATE = 76800

CDEFS += \
  CONFIG_MINIMAL_SYSTEM=1 \
  CONFIG_PIN=1 \
  CONFIG_DHT=1 \
  CONFIG_START_SHELL=1 \
  CONFIG_DHT_COMMAND_READ=1

MAIN_C = src/main.c

include $(SIMBA_ROOT)/make/app.mk
